<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFLgY7xe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFLgY7xe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFLgY7xe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFLgY7xe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFLgY7xe\App_KernelDevDebugContainer([
    'container.build_hash' => 'FLgY7xe',
    'container.build_id' => 'f75622b4',
    'container.build_time' => 1691166159,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFLgY7xe');
