<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSNNN45y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSNNN45y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSNNN45y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSNNN45y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSNNN45y\App_KernelDevDebugContainer([
    'container.build_hash' => 'SNNN45y',
    'container.build_id' => '2fbe8980',
    'container.build_time' => 1691338989,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSNNN45y');
